### ISSUE TITLE
Trying out deltwitter php script - feedback from tests

### ISSUE THREAD

**Issue by niclaz** [yahesh/deltwitter#1]
## Testing out this script so as to assist in deleting the 1300+ tweets on my profile in twitter 

**DISCLAIMER**: Not a PHP expert, so had a learning curve to figure out `composer` and the dependencies, apologies if my feedback seems evident to a PHP dev. 

I ran the script a few times and keep getting 'FAILED' returns and after about 100 requests the terminal spits out:

`PHP Fatal error:  Uncaught Abraham\TwitterOAuth\TwitterOAuthException: Operation timed out after 30000 milliseconds with 0 bytes received in /home/user/Documents/packages - linux software/deltwitter-main/vendor/abraham/twitteroauth/src/TwitterOAuth.php:715`

I am still debugging - so this is not an issue regarding the error, just submitting my feedback as I go for you to improve this repo and help others who may be facing first-time issues with it...

#Feedback from first attempt at use of the script:

- In preparation phase of the readme.md the requesting of the Twitter Archive is step 7, this process took over 24 hours for Twitter to complete. Would recommend putting this higher up so that someone like me can request the archive and start building the environment for the script to run. 

- Similar as above, it is not evident where the archive zip goes (any location within system) and whether all you need is the tweet.js file or the whole archive to be present. Some more words in step 7 to clarify this might help a novice user. 

- Step 2/3 discuss the Twitter Developer Portal for the user to create API access token & secret, unsure if this something new but it seems currently that the default API token only allow the script 'read access' to the platform. I have generated a OAuth 2.0 token now and will continue testing to see if that was the reason the first few runs were failing. A note or extra step about this would be useful for those people that do not usually develop apps on Twitter, just a suggestion.

- Composer and dependencies: not knowing too much about PHP I had to spend some time understanding this package manager, and seeking the appropriate dependencies for abraham/twitteroauth to run. As such would be great to have a section in the readme.md that lists these for the person looking over the repo and having a link to [packagist](https://packagist.org/packages/abraham/twitteroauth) for them to look at. Related to this I struggled to get ext-curl within composer (throws several errors) which I fixed using cURL instead... running `composer require curl/curl` ... I am unsure if this is new or something already fixed within the twitteroauth [code](https://github.com/abraham/twitteroauth) that I have not come across.

That is all for now, will keep trying to get the script to run and provide more feedback if necessary. 

If I get stuck fully I may open a real issue here asking for support.

**Comment by niclaz** [comment]
Update: been trying to debug for last few hours - threw the project workspace out and started again from scratch. 

Have not managed to delete a tweet as of yet - I think it is working as intended as my terminal shows 'FAILED: <tweet id>' until it hits the error noted above.

I am sensing I am missing a step in Twitter API authentication... but I may be wrong as the script does run and lists

That said I am able to send curl GET requests with the API and bearer tokens successfully....

Will give it another go tomorrow

**Comment by niclaz** [comment]
Found this news tweeted last week by @TwitterDev - could be the reason why the script was not working for me **shrug**

_Starting February 9, we will no longer support free access to the Twitter API, both v2 and v1.1. A paid basic tier will be available instead_ 

https://twitter.com/TwitterDev/status/1621026986784337922

**Comment by yahesh** [comment]
First, I'm starting by citing the [readme](https://github.com/yahesh/deltwitter#things-to-note):

> _"This script was written with the intention to be a lowest-effort approach to automating the deletion of tweets and retweets. If it breaks anything, it is up to you to fix it. There will be absolutely no support given to anyone using this script. You have been warned."_

Secondly, yes, Twitter has mentioned to restrict the API to posting-only functionality. Given the erratic _"management"_ style of Elmo Tusk, it's possible that this limitation will be rescinded sometime in the future.

As you only try to delete about ~1300 tweets, you might be lucky, that there is a delete-all-tweets website out there that still works and is sufficient for your task. This script was written when I had >100.000 tweets around which was too much for API-based delete-all-tweets websites.

Will close this as **wontfix**.

**Comment by niclaz** [comment]
100% - not asking for support or for you to fix anything @yahesh. Just providing feedback from testing the script and code.

Just providing feedback to you, thanks regardless for the repo - learnt a fair amount about PHP and composer
